package LibraryModel;
// Generated May 20, 2020 1:50:33 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Book generated by hbm2java
 */
public class Book  implements java.io.Serializable {


     private String bookid;
     private String title;
     private String publishinghouse;
     private Date dateofpublication;
     private String author;
     private String pages;
     private String numberofcopies;
     private String bookcategory;

    public Book() {
    }

	
    public Book(String bookid, String pages, String numberofcopies) {
        this.bookid = bookid;
        this.pages = pages;
        this.numberofcopies = numberofcopies;
    }
    public Book(String bookid, String title, String publishinghouse, Date dateofpublication, String author, String pages, String numberofcopies, String bookcategory) {
       this.bookid = bookid;
       this.title = title;
       this.publishinghouse = publishinghouse;
       this.dateofpublication = dateofpublication;
       this.author = author;
       this.pages = pages;
       this.numberofcopies = numberofcopies;
       this.bookcategory = bookcategory;
    }
   
    public String getBookid() {
        return this.bookid;
    }
    
    public void setBookid(String bookid) {
        this.bookid = bookid;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getPublishinghouse() {
        return this.publishinghouse;
    }
    
    public void setPublishinghouse(String publishinghouse) {
        this.publishinghouse = publishinghouse;
    }
    public Date getDateofpublication() {
        return this.dateofpublication;
    }
    
    public void setDateofpublication(Date dateofpublication) {
        this.dateofpublication = dateofpublication;
    }
    public String getAuthor() {
        return this.author;
    }
    
    public void setAuthor(String author) {
        this.author = author;
    }
    public String getPages() {
        return this.pages;
    }
    
    public void setPages(String pages) {
        this.pages = pages;
    }
    public String getNumberofcopies() {
        return this.numberofcopies;
    }
    
    public void setNumberofcopies(String numberofcopies) {
        this.numberofcopies = numberofcopies;
    }
    public String getBookcategory() {
        return this.bookcategory;
    }
    
    public void setBookcategory(String bookcategory) {
        this.bookcategory = bookcategory;
    }




}


