package LibraryModel;
// Generated May 20, 2020 1:50:33 PM by Hibernate Tools 4.3.1



/**
 * Client generated by hbm2java
 */
public class Client  implements java.io.Serializable {


     private String regno;
     private String firstname;
     private String lastname;
     private String phonennumber;
     private String emailaddress;
     private String clientcategory;
     private String photo;

    public Client() {
    }

	
    public Client(String regno) {
        this.regno = regno;
    }
    public Client(String regno, String firstname, String lastname, String phonennumber, String emailaddress, String clientcategory, String photo) {
       this.regno = regno;
       this.firstname = firstname;
       this.lastname = lastname;
       this.phonennumber = phonennumber;
       this.emailaddress = emailaddress;
       this.clientcategory = clientcategory;
       this.photo = photo;
    }
   
    public String getRegno() {
        return this.regno;
    }
    
    public void setRegno(String regno) {
        this.regno = regno;
    }
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public String getPhonennumber() {
        return this.phonennumber;
    }
    
    public void setPhonennumber(String phonennumber) {
        this.phonennumber = phonennumber;
    }
    public String getEmailaddress() {
        return this.emailaddress;
    }
    
    public void setEmailaddress(String emailaddress) {
        this.emailaddress = emailaddress;
    }
    public String getClientcategory() {
        return this.clientcategory;
    }
    
    public void setClientcategory(String clientcategory) {
        this.clientcategory = clientcategory;
    }
    public String getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(String photo) {
        this.photo = photo;
    }




}


