package LibraryModel;
// Generated May 20, 2020 1:50:33 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Repport generated by hbm2java
 */
public class Repport  implements java.io.Serializable {


     private String id;
     private String bookname;
     private Date fromdate;
     private Date todate;
     private String options;

    public Repport() {
    }

	
    public Repport(String id, String options) {
        this.id = id;
        this.options = options;
    }
    public Repport(String id, String bookname, Date fromdate, Date todate, String options) {
       this.id = id;
       this.bookname = bookname;
       this.fromdate = fromdate;
       this.todate = todate;
       this.options = options;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getBookname() {
        return this.bookname;
    }
    
    public void setBookname(String bookname) {
        this.bookname = bookname;
    }
    public Date getFromdate() {
        return this.fromdate;
    }
    
    public void setFromdate(Date fromdate) {
        this.fromdate = fromdate;
    }
    public Date getTodate() {
        return this.todate;
    }
    
    public void setTodate(Date todate) {
        this.todate = todate;
    }
    public String getOptions() {
        return this.options;
    }
    
    public void setOptions(String options) {
        this.options = options;
    }




}


